
listaDeArgumentos:
	g++ -c listaDeArgumentos.c
	g++ -o listaDeArgumentos listaDeArgumentos.c

manejoDeArgumentos:
	g++ -c manejoDeArgumentos.c
	g++ -o manejoDeArgumentos manejoDeArgumentos.c

ejemplo1:
	g++ -c ejemplo1.c
	g++ -o ejemplo1 ejemplo1.c

javaArgumentos:
	javac holaMundo.java

variablesDeAmbiente:
	g++ -c variablesDeAmbiente.c
	g++ -o variablesDeAmbiente variablesDeAmbiente.c

ejemplo2:
	g++ -c ejemplo2.c
	g++ -o ejemplo2 ejemplo2.c

LEnviroment:
	g++ -c LEnviroment.c
	g++ -o LEnviroment LEnviroment.c

Wenviroment:
	g++ -c Wenviroment.c
	g++ -o Wenviroment Wenviroment.c

javaVariables:
	javac variablesJava.java

errno:
	g++ -c errno.c
	g++ -o errno errno.c

clean:
	rm -f listaDeArgumentos
	rm -f manejoDeArgumentos
	rm -f ejemplo1
	rm -f ejemplo2
	rm -f variablesDeAmbiente
	rm -f LEnviroment
	rm -f Wenviroment
	rm -f errno
	rm -f *.class
	rm  -f *.o


	