Lfork:
	g++ -c Lfork.c
	g++ -o Lfork Lfork.c

EjemploFork:
	g++ -c EjemploFork.c
	g++ -o EjemploFork EjemploFork.c

LDirectorioActual:
	g++ -c LDirectorioActual.c
	g++ -o LDirectorioActual LDirectorioActual.c

ejercicio1:
	g++ -c ejercicio1.c
	g++ -o ejercicio1 ejercicio1.c

ejercicio2:
	g++ -c ejercicio2.c
	g++ -o ejercicio2 ejercicio2.c

LProcesoSinSeñal:
	g++ -c LProcesoSinSeñal.c
	g++ -o LProcesoSinSeñal LProcesoSinSeñal.c

LProcesoConSeñal:
	g++ -c LProcesoConSeñal.c
	g++ -o LProcesoConSeñal LProcesoConSeñal.c

LCrearPThread:
	g++ -c LCrearPThread.c
	g++ -o LCrearPThread LCrearPThread.c -pthread

clean:
	rm -f Lfork
	rm -f EjemploFork 	
	rm -f LDirectorioActual
	rm -f ejercicio1
	rm -f ejercicio2
	rm -f LProcesoSinSeñal
	rm -f LProcesoConSeñal
	rm -f LCrearPThread
	rm -f *.class
	rm  -f *.o


	